config:
  aws:region: us-east-1
  infra:dbToken:
    secure: AAABAGdNTdlaicdqlfOrviGAAAxEl/SkfyrbnCdmlSESIVx2XQAVe+DFVkk4HtLJAMJU39hYEhdG8J/BvPyu5b4wg1UK1exDQIPMF44OTQuISIBnxdOnjwcE7baEtTGgrcMXA7IhiznC/3xwHJwNLAkIb26HNq7BhgXo7U82HxmgwY1+ZObFuanXW9XZvWLKUrCA4j7AZjO5+MNgZp6aLLho2y3+8jSUlIehGkNbUsYnFK4vy6eZjZbJ5/kM6GOcZ+hScIC9oEOoHT/blrzPMLkV7wU/qGG+ZUkAbfQqJV4Gf9lamsNg9xuHjeuXC9vkU5M8ltY1kjf8gKY=
  infra:dbUrl: "libsql://my-turborepo-geraudi.turso.io"
